// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/rpc_messages.proto
// Protobuf Java Version: 4.28.3

package rpc.v2.cache.common.message;

public final class RpcMessages {
  private RpcMessages() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      RpcMessages.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.custom.common.message.RpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The name of the interface to be invoked
     * </pre>
     *
     * <code>string interfaceName = 1;</code>
     * @return The interfaceName.
     */
    String getInterfaceName();
    /**
     * <pre>
     * The name of the interface to be invoked
     * </pre>
     *
     * <code>string interfaceName = 1;</code>
     * @return The bytes for interfaceName.
     */
    com.google.protobuf.ByteString
        getInterfaceNameBytes();

    /**
     * <pre>
     * The name of the method to be invoked
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    String getMethodName();
    /**
     * <pre>
     * The name of the method to be invoked
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <pre>
     * Serialized parameters as bytes
     * </pre>
     *
     * <code>repeated bytes parameters = 3;</code>
     * @return A list containing the parameters.
     */
    java.util.List<com.google.protobuf.ByteString> getParametersList();
    /**
     * <pre>
     * Serialized parameters as bytes
     * </pre>
     *
     * <code>repeated bytes parameters = 3;</code>
     * @return The count of parameters.
     */
    int getParametersCount();
    /**
     * <pre>
     * Serialized parameters as bytes
     * </pre>
     *
     * <code>repeated bytes parameters = 3;</code>
     * @param index The index of the element to return.
     * @return The parameters at the given index.
     */
    com.google.protobuf.ByteString getParameters(int index);

    /**
     * <pre>
     * Parameter types as class names
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @return A list containing the paramTypes.
     */
    java.util.List<String>
        getParamTypesList();
    /**
     * <pre>
     * Parameter types as class names
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @return The count of paramTypes.
     */
    int getParamTypesCount();
    /**
     * <pre>
     * Parameter types as class names
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the element to return.
     * @return The paramTypes at the given index.
     */
    String getParamTypes(int index);
    /**
     * <pre>
     * Parameter types as class names
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramTypes at the given index.
     */
    com.google.protobuf.ByteString
        getParamTypesBytes(int index);
  }
  /**
   * <pre>
   * RpcRequest message definition
   * </pre>
   *
   * Protobuf type {@code rpc.custom.common.message.RpcRequest}
   */
  public static final class RpcRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rpc.custom.common.message.RpcRequest)
      RpcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        RpcRequest.class.getName());
    }
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RpcRequest() {
      interfaceName_ = "";
      methodName_ = "";
      parameters_ = emptyList(com.google.protobuf.ByteString.class);
      paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcMessages.internal_static_rpc_custom_common_message_RpcRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcMessages.internal_static_rpc_custom_common_message_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcRequest.class, Builder.class);
    }

    public static final int INTERFACENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object interfaceName_ = "";
    /**
     * <pre>
     * The name of the interface to be invoked
     * </pre>
     *
     * <code>string interfaceName = 1;</code>
     * @return The interfaceName.
     */
    @Override
    public String getInterfaceName() {
      Object ref = interfaceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        interfaceName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The name of the interface to be invoked
     * </pre>
     *
     * <code>string interfaceName = 1;</code>
     * @return The bytes for interfaceName.
     */
    @Override
    public com.google.protobuf.ByteString
        getInterfaceNameBytes() {
      Object ref = interfaceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        interfaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object methodName_ = "";
    /**
     * <pre>
     * The name of the method to be invoked
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    @Override
    public String getMethodName() {
      Object ref = methodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The name of the method to be invoked
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    @Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETERS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> parameters_ =
        emptyList(com.google.protobuf.ByteString.class);
    /**
     * <pre>
     * Serialized parameters as bytes
     * </pre>
     *
     * <code>repeated bytes parameters = 3;</code>
     * @return A list containing the parameters.
     */
    @Override
    public java.util.List<com.google.protobuf.ByteString>
        getParametersList() {
      return parameters_;
    }
    /**
     * <pre>
     * Serialized parameters as bytes
     * </pre>
     *
     * <code>repeated bytes parameters = 3;</code>
     * @return The count of parameters.
     */
    public int getParametersCount() {
      return parameters_.size();
    }
    /**
     * <pre>
     * Serialized parameters as bytes
     * </pre>
     *
     * <code>repeated bytes parameters = 3;</code>
     * @param index The index of the element to return.
     * @return The parameters at the given index.
     */
    public com.google.protobuf.ByteString getParameters(int index) {
      return parameters_.get(index);
    }

    public static final int PARAMTYPES_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList paramTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * Parameter types as class names
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @return A list containing the paramTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getParamTypesList() {
      return paramTypes_;
    }
    /**
     * <pre>
     * Parameter types as class names
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @return The count of paramTypes.
     */
    public int getParamTypesCount() {
      return paramTypes_.size();
    }
    /**
     * <pre>
     * Parameter types as class names
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the element to return.
     * @return The paramTypes at the given index.
     */
    public String getParamTypes(int index) {
      return paramTypes_.get(index);
    }
    /**
     * <pre>
     * Parameter types as class names
     * </pre>
     *
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getParamTypesBytes(int index) {
      return paramTypes_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(interfaceName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, interfaceName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, methodName_);
      }
      for (int i = 0; i < parameters_.size(); i++) {
        output.writeBytes(3, parameters_.get(i));
      }
      for (int i = 0; i < paramTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, paramTypes_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(interfaceName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, interfaceName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, methodName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameters_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parameters_.get(i));
        }
        size += dataSize;
        size += 1 * getParametersList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(paramTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamTypesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RpcRequest)) {
        return super.equals(obj);
      }
      RpcRequest other = (RpcRequest) obj;

      if (!getInterfaceName()
          .equals(other.getInterfaceName())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParametersList()
          .equals(other.getParametersList())) return false;
      if (!getParamTypesList()
          .equals(other.getParamTypesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTERFACENAME_FIELD_NUMBER;
      hash = (53 * hash) + getInterfaceName().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getParametersCount() > 0) {
        hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + getParametersList().hashCode();
      }
      if (getParamTypesCount() > 0) {
        hash = (37 * hash) + PARAMTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParamTypesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RpcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * RpcRequest message definition
     * </pre>
     *
     * Protobuf type {@code rpc.custom.common.message.RpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.custom.common.message.RpcRequest)
        RpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcMessages.internal_static_rpc_custom_common_message_RpcRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcMessages.internal_static_rpc_custom_common_message_RpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RpcRequest.class, Builder.class);
      }

      // Construct using rpc.custom.common.message.RpcMessages.RpcRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        interfaceName_ = "";
        methodName_ = "";
        parameters_ = emptyList(com.google.protobuf.ByteString.class);
        paramTypes_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcMessages.internal_static_rpc_custom_common_message_RpcRequest_descriptor;
      }

      @Override
      public RpcRequest getDefaultInstanceForType() {
        return RpcRequest.getDefaultInstance();
      }

      @Override
      public RpcRequest build() {
        RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RpcRequest buildPartial() {
        RpcRequest result = new RpcRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(RpcRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.interfaceName_ = interfaceName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.methodName_ = methodName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          parameters_.makeImmutable();
          result.parameters_ = parameters_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          paramTypes_.makeImmutable();
          result.paramTypes_ = paramTypes_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RpcRequest) {
          return mergeFrom((RpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RpcRequest other) {
        if (other == RpcRequest.getDefaultInstance()) return this;
        if (!other.getInterfaceName().isEmpty()) {
          interfaceName_ = other.interfaceName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.parameters_.isEmpty()) {
          if (parameters_.isEmpty()) {
            parameters_ = other.parameters_;
            parameters_.makeImmutable();
            bitField0_ |= 0x00000004;
          } else {
            ensureParametersIsMutable();
            parameters_.addAll(other.parameters_);
          }
          onChanged();
        }
        if (!other.paramTypes_.isEmpty()) {
          if (paramTypes_.isEmpty()) {
            paramTypes_ = other.paramTypes_;
            bitField0_ |= 0x00000008;
          } else {
            ensureParamTypesIsMutable();
            paramTypes_.addAll(other.paramTypes_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                interfaceName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                methodName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureParametersIsMutable();
                parameters_.add(v);
                break;
              } // case 26
              case 34: {
                String s = input.readStringRequireUtf8();
                ensureParamTypesIsMutable();
                paramTypes_.add(s);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object interfaceName_ = "";
      /**
       * <pre>
       * The name of the interface to be invoked
       * </pre>
       *
       * <code>string interfaceName = 1;</code>
       * @return The interfaceName.
       */
      public String getInterfaceName() {
        Object ref = interfaceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          interfaceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * The name of the interface to be invoked
       * </pre>
       *
       * <code>string interfaceName = 1;</code>
       * @return The bytes for interfaceName.
       */
      public com.google.protobuf.ByteString
          getInterfaceNameBytes() {
        Object ref = interfaceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          interfaceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The name of the interface to be invoked
       * </pre>
       *
       * <code>string interfaceName = 1;</code>
       * @param value The interfaceName to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        interfaceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name of the interface to be invoked
       * </pre>
       *
       * <code>string interfaceName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterfaceName() {
        interfaceName_ = getDefaultInstance().getInterfaceName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name of the interface to be invoked
       * </pre>
       *
       * <code>string interfaceName = 1;</code>
       * @param value The bytes for interfaceName to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        interfaceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object methodName_ = "";
      /**
       * <pre>
       * The name of the method to be invoked
       * </pre>
       *
       * <code>string methodName = 2;</code>
       * @return The methodName.
       */
      public String getMethodName() {
        Object ref = methodName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * The name of the method to be invoked
       * </pre>
       *
       * <code>string methodName = 2;</code>
       * @return The bytes for methodName.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The name of the method to be invoked
       * </pre>
       *
       * <code>string methodName = 2;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        methodName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name of the method to be invoked
       * </pre>
       *
       * <code>string methodName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        methodName_ = getDefaultInstance().getMethodName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name of the method to be invoked
       * </pre>
       *
       * <code>string methodName = 2;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        methodName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> parameters_ = emptyList(com.google.protobuf.ByteString.class);
      private void ensureParametersIsMutable() {
        if (!parameters_.isModifiable()) {
          parameters_ = makeMutableCopy(parameters_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <pre>
       * Serialized parameters as bytes
       * </pre>
       *
       * <code>repeated bytes parameters = 3;</code>
       * @return A list containing the parameters.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getParametersList() {
        parameters_.makeImmutable();
        return parameters_;
      }
      /**
       * <pre>
       * Serialized parameters as bytes
       * </pre>
       *
       * <code>repeated bytes parameters = 3;</code>
       * @return The count of parameters.
       */
      public int getParametersCount() {
        return parameters_.size();
      }
      /**
       * <pre>
       * Serialized parameters as bytes
       * </pre>
       *
       * <code>repeated bytes parameters = 3;</code>
       * @param index The index of the element to return.
       * @return The parameters at the given index.
       */
      public com.google.protobuf.ByteString getParameters(int index) {
        return parameters_.get(index);
      }
      /**
       * <pre>
       * Serialized parameters as bytes
       * </pre>
       *
       * <code>repeated bytes parameters = 3;</code>
       * @param index The index to set the value at.
       * @param value The parameters to set.
       * @return This builder for chaining.
       */
      public Builder setParameters(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParametersIsMutable();
        parameters_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Serialized parameters as bytes
       * </pre>
       *
       * <code>repeated bytes parameters = 3;</code>
       * @param value The parameters to add.
       * @return This builder for chaining.
       */
      public Builder addParameters(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParametersIsMutable();
        parameters_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Serialized parameters as bytes
       * </pre>
       *
       * <code>repeated bytes parameters = 3;</code>
       * @param values The parameters to add.
       * @return This builder for chaining.
       */
      public Builder addAllParameters(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureParametersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameters_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Serialized parameters as bytes
       * </pre>
       *
       * <code>repeated bytes parameters = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParameters() {
        parameters_ = emptyList(com.google.protobuf.ByteString.class);
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureParamTypesIsMutable() {
        if (!paramTypes_.isModifiable()) {
          paramTypes_ = new com.google.protobuf.LazyStringArrayList(paramTypes_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <pre>
       * Parameter types as class names
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @return A list containing the paramTypes.
       */
      public com.google.protobuf.ProtocolStringList
          getParamTypesList() {
        paramTypes_.makeImmutable();
        return paramTypes_;
      }
      /**
       * <pre>
       * Parameter types as class names
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @return The count of paramTypes.
       */
      public int getParamTypesCount() {
        return paramTypes_.size();
      }
      /**
       * <pre>
       * Parameter types as class names
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param index The index of the element to return.
       * @return The paramTypes at the given index.
       */
      public String getParamTypes(int index) {
        return paramTypes_.get(index);
      }
      /**
       * <pre>
       * Parameter types as class names
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the paramTypes at the given index.
       */
      public com.google.protobuf.ByteString
          getParamTypesBytes(int index) {
        return paramTypes_.getByteString(index);
      }
      /**
       * <pre>
       * Parameter types as class names
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param index The index to set the value at.
       * @param value The paramTypes to set.
       * @return This builder for chaining.
       */
      public Builder setParamTypes(
          int index, String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamTypesIsMutable();
        paramTypes_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Parameter types as class names
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param value The paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamTypes(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamTypesIsMutable();
        paramTypes_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Parameter types as class names
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param values The paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllParamTypes(
          Iterable<String> values) {
        ensureParamTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paramTypes_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Parameter types as class names
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearParamTypes() {
        paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Parameter types as class names
       * </pre>
       *
       * <code>repeated string paramTypes = 4;</code>
       * @param value The bytes of the paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureParamTypesIsMutable();
        paramTypes_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rpc.custom.common.message.RpcRequest)
    }

    // @@protoc_insertion_point(class_scope:rpc.custom.common.message.RpcRequest)
    private static final RpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RpcRequest();
    }

    public static RpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
      @Override
      public RpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RpcRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RpcRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public RpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RpcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.custom.common.message.RpcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Response status code
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     * Response message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    String getMessage();
    /**
     * <pre>
     * Response message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * Serialized data as bytes
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <pre>
     * Class name of the data type
     * </pre>
     *
     * <code>string dataType = 4;</code>
     * @return The dataType.
     */
    String getDataType();
    /**
     * <pre>
     * Class name of the data type
     * </pre>
     *
     * <code>string dataType = 4;</code>
     * @return The bytes for dataType.
     */
    com.google.protobuf.ByteString
        getDataTypeBytes();
  }
  /**
   * <pre>
   * RpcResponse message definition
   * </pre>
   *
   * Protobuf type {@code rpc.custom.common.message.RpcResponse}
   */
  public static final class RpcResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rpc.custom.common.message.RpcResponse)
      RpcResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        RpcResponse.class.getName());
    }
    // Use RpcResponse.newBuilder() to construct.
    private RpcResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RpcResponse() {
      message_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      dataType_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcMessages.internal_static_rpc_custom_common_message_RpcResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcMessages.internal_static_rpc_custom_common_message_RpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcResponse.class, Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_ = 0;
    /**
     * <pre>
     * Response status code
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object message_ = "";
    /**
     * <pre>
     * Response message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @Override
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Response message
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Serialized data as bytes
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int DATATYPE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object dataType_ = "";
    /**
     * <pre>
     * Class name of the data type
     * </pre>
     *
     * <code>string dataType = 4;</code>
     * @return The dataType.
     */
    @Override
    public String getDataType() {
      Object ref = dataType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dataType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Class name of the data type
     * </pre>
     *
     * <code>string dataType = 4;</code>
     * @return The bytes for dataType.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataTypeBytes() {
      Object ref = dataType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, dataType_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, dataType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RpcResponse)) {
        return super.equals(obj);
      }
      RpcResponse other = (RpcResponse) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getDataType()
          .equals(other.getDataType())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDataType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RpcResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static RpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static RpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static RpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RpcResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * RpcResponse message definition
     * </pre>
     *
     * Protobuf type {@code rpc.custom.common.message.RpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.custom.common.message.RpcResponse)
        RpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcMessages.internal_static_rpc_custom_common_message_RpcResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcMessages.internal_static_rpc_custom_common_message_RpcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RpcResponse.class, Builder.class);
      }

      // Construct using rpc.custom.common.message.RpcMessages.RpcResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = 0;
        message_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
        dataType_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcMessages.internal_static_rpc_custom_common_message_RpcResponse_descriptor;
      }

      @Override
      public RpcResponse getDefaultInstanceForType() {
        return RpcResponse.getDefaultInstance();
      }

      @Override
      public RpcResponse build() {
        RpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RpcResponse buildPartial() {
        RpcResponse result = new RpcResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(RpcResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.data_ = data_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.dataType_ = dataType_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RpcResponse) {
          return mergeFrom((RpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RpcResponse other) {
        if (other == RpcResponse.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.getDataType().isEmpty()) {
          dataType_ = other.dataType_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                code_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                dataType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       * Response status code
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * Response status code
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Response status code
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <pre>
       * Response message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Response message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Response message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Response message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Response message
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Serialized data as bytes
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * Serialized data as bytes
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Serialized data as bytes
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private Object dataType_ = "";
      /**
       * <pre>
       * Class name of the data type
       * </pre>
       *
       * <code>string dataType = 4;</code>
       * @return The dataType.
       */
      public String getDataType() {
        Object ref = dataType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dataType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Class name of the data type
       * </pre>
       *
       * <code>string dataType = 4;</code>
       * @return The bytes for dataType.
       */
      public com.google.protobuf.ByteString
          getDataTypeBytes() {
        Object ref = dataType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dataType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Class name of the data type
       * </pre>
       *
       * <code>string dataType = 4;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        dataType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Class name of the data type
       * </pre>
       *
       * <code>string dataType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        dataType_ = getDefaultInstance().getDataType();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Class name of the data type
       * </pre>
       *
       * <code>string dataType = 4;</code>
       * @param value The bytes for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dataType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rpc.custom.common.message.RpcResponse)
    }

    // @@protoc_insertion_point(class_scope:rpc.custom.common.message.RpcResponse)
    private static final RpcResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RpcResponse();
    }

    public static RpcResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcResponse>
        PARSER = new com.google.protobuf.AbstractParser<RpcResponse>() {
      @Override
      public RpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RpcResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RpcResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public RpcResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_custom_common_message_RpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_custom_common_message_RpcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_custom_common_message_RpcResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_custom_common_message_RpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n!src/main/proto/rpc_messages.proto\022\031rpc" +
      ".custom.common.message\"_\n\nRpcRequest\022\025\n\r" +
      "interfaceName\030\001 \001(\t\022\022\n\nmethodName\030\002 \001(\t\022" +
      "\022\n\nparameters\030\003 \003(\014\022\022\n\nparamTypes\030\004 \003(\t\"" +
      "L\n\013RpcResponse\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030" +
      "\002 \001(\t\022\014\n\004data\030\003 \001(\014\022\020\n\010dataType\030\004 \001(\tb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rpc_custom_common_message_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_custom_common_message_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_custom_common_message_RpcRequest_descriptor,
        new String[] { "InterfaceName", "MethodName", "Parameters", "ParamTypes", });
    internal_static_rpc_custom_common_message_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_custom_common_message_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_custom_common_message_RpcResponse_descriptor,
        new String[] { "Code", "Message", "Data", "DataType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
